version: '3'
services:
  notebook:
    build: ./libraries
    environment: 
      - "TZ=Asia/Tokyo"
    volumes:
      - ./experiments:/home/jovyan/data/
    ports:
      - "8888:8888"
    networks:
      - default

networks:
  default:  
    driver: bridge